name: kzn
description: A new learning mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # image slider
  carousel_slider: ^2.1.0
  # serialization
  json_annotation: ^3.1.1
  # state management
  provider: ^5.0.0
  # http api
  # http: ^0.12.2
  dio: ^4.0.0
  # shared preferences
  shared_preferences: ^2.0.5
  # intro slider
  intro_slider: ^2.3.3
  # rating bar
  flutter_rating_bar: ^4.0.0
  # sweet alert
  sweetalert: ^0.0.1
  # search bar
  flutter_search_bar: ^2.1.0
  # webview
  webview_flutter: ^2.0.4
  # open facebook
  url_launcher: ^6.0.3
  # loading modal
  modal_progress_hud: ^0.1.3
  # video player
  better_player: ^0.0.70
  font_awesome_flutter: ^9.2.0
  change_app_package_name: ^1.0.0
  http: ^0.13.4
  flutter_html: ^2.0.0

dev_dependencies:
  build_runner: ^1.10.9
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/slider/
